openapi: 3.0.1
info:
  title: Voytekgar - org - puste 3
  x-cortex-git:
    github:
      alias: voytekgar
      repository: voytekgar-org/puste
  x-cortex-tag: puste-on-root
  x-cortex-type: service
