openapi: 3.1.0
info:
  title: Voytekgar - org - puste nested 8
  x-cortex-git:
    github:
      alias: voytekgar
      repository: voytekgar-org/puste
  x-cortex-tag: puste-nested
  x-cortex-type: service
